export default {
  "Colleague": {
    "ColleagueId": "E001",
    "FirstName": "Luan",
    "LastName": "Au",
    "KnownAsName": "",
    "EmailAddress": "Luan.Au@domain.com",
    "Department": "",
    "Grade": "",
    "Division": "",
    "ManagerId": "E0010",
    "HasManager": true,
    "Manager": {
      "ColleagueId": "E0010",
      "FirstName": "Sandip",
      "LastName": "Vaidya",
      "KnownAsName": "",
      "EmailAddress": "Sandip.Vaidya@domain.com",
      "Department": "",
      "Grade": "SM",
      "Division": "",
      "ManagerId": "E0011",
      "HasManager": false,
      "Manager": null,
      "JobTitle": "Developer",
      "CostCode": "N4426 ",
      "JobCode": "Z0003",
      "L1": "J Sainsbury Plc",
      "L2": "Central",
      "L3": "Digital & Technology Division",
      "L4": "Digital & Technology",
      "L5": "N1234 - D&T Business Partnering Customer & Colleague",
      "IsContractor": false,
      "IsAManager": true,
      "IsActive": true,
      "SuperUserAccessLevel": 1,
      "FullName": "Sandip Vaidya"
    },
    "JobTitle": "Developer",
    "CostCode": "valueCostCode",
    "JobCode": "valueJobCode",
    "L1": "J Sainsbury Plc",
    "L2": "Central",
    "L3": "Digital & Technology Division",
    "L4": "Digital & Technology",
    "L5": "N1234 - D&T Business Partnering Customer & Colleague",
    "IsContractor": false,
    "IsAManager": false,
    "IsActive": true,
    "SuperUserAccessLevel": 0,
    "FullName": "Luan Au"
  },
  "Meetings": [
    {
      "MeetingId": 6,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-15T14:07:05.89",
      "ColleagueSignedOffDate": "2016-07-15T14:07:05.89",
      "ManagerSignedOffDate": "2016-07-15T14:07:05.89",
      "SharingStatus": 1,
      "SharingDate": "2016-07-15T14:07:05.89",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1004,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 0,
      "ManagerSignOff": 0,
      "Status": 0,
      "MeetingDate": "2016-09-26T13:42:00",
      "ColleagueSignedOffDate": null,
      "ManagerSignedOffDate": null,
      "SharingStatus": 0,
      "SharingDate": null,
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1005,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-09-26T12:43:00",
      "ColleagueSignedOffDate": "2016-11-17T10:53:54.417",
      "ManagerSignedOffDate": "2016-11-18T08:44:11.14",
      "SharingStatus": 1,
      "SharingDate": "2016-11-17T10:53:54.417",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1010,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:42:11.937",
      "ColleagueSignedOffDate": "2016-07-30T12:42:11.937",
      "ManagerSignedOffDate": "2016-07-30T12:42:11.937",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:42:11.937",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1035,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:46:32.327",
      "ColleagueSignedOffDate": "2016-07-30T12:46:32.327",
      "ManagerSignedOffDate": "2016-07-30T12:46:32.327",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:46:32.327",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1037,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:46:32.33",
      "ColleagueSignedOffDate": "2016-07-30T12:46:32.33",
      "ManagerSignedOffDate": "2016-07-30T12:46:32.33",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:46:32.33",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1039,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:46:32.33",
      "ColleagueSignedOffDate": "2016-07-30T12:46:32.33",
      "ManagerSignedOffDate": "2016-07-30T12:46:32.33",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:46:32.33",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1041,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:46:32.33",
      "ColleagueSignedOffDate": "2016-07-30T12:46:32.33",
      "ManagerSignedOffDate": "2016-07-30T12:46:32.33",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:46:32.33",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1074,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:47:08.203",
      "ColleagueSignedOffDate": "2016-07-30T12:47:08.203",
      "ManagerSignedOffDate": "2016-07-30T12:47:08.203",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:47:08.203",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1076,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:47:08.203",
      "ColleagueSignedOffDate": "2016-07-30T12:47:08.203",
      "ManagerSignedOffDate": "2016-07-30T12:47:08.203",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:47:08.203",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1078,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:47:08.207",
      "ColleagueSignedOffDate": "2016-07-30T12:47:08.207",
      "ManagerSignedOffDate": "2016-07-30T12:47:08.207",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:47:08.207",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 1080,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-07-30T12:47:08.207",
      "ColleagueSignedOffDate": "2016-07-30T12:47:08.207",
      "ManagerSignedOffDate": "2016-07-30T12:47:08.207",
      "SharingStatus": 1,
      "SharingDate": "2016-07-30T12:47:08.207",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 2007,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-10-20T10:04:00",
      "ColleagueSignedOffDate": "2016-11-18T09:42:12.917",
      "ManagerSignedOffDate": "2016-11-18T10:04:24.727",
      "SharingStatus": 1,
      "SharingDate": "2016-11-18T09:42:12.917",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 2009,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-10-20T10:41:00",
      "ColleagueSignedOffDate": "2016-11-18T15:28:49.85",
      "ManagerSignedOffDate": "2016-11-18T15:31:05.397",
      "SharingStatus": 1,
      "SharingDate": "2016-11-18T15:28:49.85",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 2010,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E0010",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": {
        "ColleagueId": "E0010",
        "FirstName": "Sandip",
        "LastName": "Vaidya",
        "KnownAsName": "",
        "EmailAddress": "Sandip.Vaidya@domain.com",
        "Department": "",
        "Grade": "SM",
        "Division": "",
        "ManagerId": "E0011",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0011",
          "FirstName": "Mike",
          "LastName": "Gwyer",
          "KnownAsName": "",
          "EmailAddress": "Mike.Gwyer@domain.com",
          "Department": "",
          "Grade": "",
          "Division": "",
          "ManagerId": "E0017",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "valueCostCode",
          "JobCode": "valueJobCode",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 0,
          "FullName": "Mike Gwyer"
        },
        "JobTitle": "Developer",
        "CostCode": "N4426 ",
        "JobCode": "Z0003",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": true,
        "IsActive": true,
        "SuperUserAccessLevel": 1,
        "FullName": "Sandip Vaidya"
      },
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-10-20T09:56:00",
      "ColleagueSignedOffDate": "2016-11-18T15:47:03.677",
      "ManagerSignedOffDate": "2016-11-21T11:11:19.777",
      "SharingStatus": 1,
      "SharingDate": "2016-11-18T15:47:03.677",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 2011,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-10-20T10:00:00",
      "ColleagueSignedOffDate": "2016-11-18T15:45:19.01",
      "ManagerSignedOffDate": "2016-11-21T10:52:49.87",
      "SharingStatus": 1,
      "SharingDate": "2016-11-18T15:45:19.01",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 2012,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-10-20T09:07:00",
      "ColleagueSignedOffDate": "2016-11-16T15:35:52.703",
      "ManagerSignedOffDate": "2016-11-17T15:53:52.843",
      "SharingStatus": 1,
      "SharingDate": "2016-11-16T15:35:52.703",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 3006,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-10-27T06:10:00",
      "ColleagueSignedOffDate": "2016-11-16T15:47:19.677",
      "ManagerSignedOffDate": "2016-11-17T09:37:25.5",
      "SharingStatus": 1,
      "SharingDate": "2016-11-16T15:47:19.677",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 3008,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E003",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": null,
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2016-11-17T11:17:00",
      "ColleagueSignedOffDate": "2016-11-17T11:19:15.333",
      "ManagerSignedOffDate": "2016-11-17T11:32:43.983",
      "SharingStatus": 1,
      "SharingDate": "2016-11-17T11:19:15.333",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 3009,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E0010",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": {
        "ColleagueId": "E0010",
        "FirstName": "Sandip",
        "LastName": "Vaidya",
        "KnownAsName": "",
        "EmailAddress": "Sandip.Vaidya@domain.com",
        "Department": "",
        "Grade": "SM",
        "Division": "",
        "ManagerId": "E0011",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0011",
          "FirstName": "Mike",
          "LastName": "Gwyer",
          "KnownAsName": "",
          "EmailAddress": "Mike.Gwyer@domain.com",
          "Department": "",
          "Grade": "",
          "Division": "",
          "ManagerId": "E0017",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "valueCostCode",
          "JobCode": "valueJobCode",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 0,
          "FullName": "Mike Gwyer"
        },
        "JobTitle": "Developer",
        "CostCode": "N4426 ",
        "JobCode": "Z0003",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": true,
        "IsActive": true,
        "SuperUserAccessLevel": 1,
        "FullName": "Sandip Vaidya"
      },
      "ColleagueSignOff": 1,
      "ManagerSignOff": 0,
      "Status": 0,
      "MeetingDate": "2016-12-12T12:36:00",
      "ColleagueSignedOffDate": "2016-12-12T12:36:57.307",
      "ManagerSignedOffDate": null,
      "SharingStatus": 1,
      "SharingDate": "2016-12-12T12:36:57.307",
      "FinancialYear": "2016-17"
    },
    {
      "MeetingId": 4009,
      "Year": null,
      "Period": null,
      "ColleagueId": "E001",
      "ManagerAtTimeId": "E0010",
      "Colleague": {
        "ColleagueId": "E001",
        "FirstName": "Luan",
        "LastName": "Au",
        "KnownAsName": "",
        "EmailAddress": "Luan.Au@domain.com",
        "Department": "",
        "Grade": "",
        "Division": "",
        "ManagerId": "E0010",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0010",
          "FirstName": "Sandip",
          "LastName": "Vaidya",
          "KnownAsName": "",
          "EmailAddress": "Sandip.Vaidya@domain.com",
          "Department": "",
          "Grade": "SM",
          "Division": "",
          "ManagerId": "E0011",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "N4426 ",
          "JobCode": "Z0003",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 1,
          "FullName": "Sandip Vaidya"
        },
        "JobTitle": "Developer",
        "CostCode": "valueCostCode",
        "JobCode": "valueJobCode",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": false,
        "IsActive": true,
        "SuperUserAccessLevel": 0,
        "FullName": "Luan Au"
      },
      "ManagerAtTime": {
        "ColleagueId": "E0010",
        "FirstName": "Sandip",
        "LastName": "Vaidya",
        "KnownAsName": "",
        "EmailAddress": "Sandip.Vaidya@domain.com",
        "Department": "",
        "Grade": "SM",
        "Division": "",
        "ManagerId": "E0011",
        "HasManager": true,
        "Manager": {
          "ColleagueId": "E0011",
          "FirstName": "Mike",
          "LastName": "Gwyer",
          "KnownAsName": "",
          "EmailAddress": "Mike.Gwyer@domain.com",
          "Department": "",
          "Grade": "",
          "Division": "",
          "ManagerId": "E0017",
          "HasManager": false,
          "Manager": null,
          "JobTitle": "Developer",
          "CostCode": "valueCostCode",
          "JobCode": "valueJobCode",
          "L1": "J Sainsbury Plc",
          "L2": "Central",
          "L3": "Digital & Technology Division",
          "L4": "Digital & Technology",
          "L5": "N1234 - D&T Business Partnering Customer & Colleague",
          "IsContractor": false,
          "IsAManager": true,
          "IsActive": true,
          "SuperUserAccessLevel": 0,
          "FullName": "Mike Gwyer"
        },
        "JobTitle": "Developer",
        "CostCode": "N4426 ",
        "JobCode": "Z0003",
        "L1": "J Sainsbury Plc",
        "L2": "Central",
        "L3": "Digital & Technology Division",
        "L4": "Digital & Technology",
        "L5": "N1234 - D&T Business Partnering Customer & Colleague",
        "IsContractor": false,
        "IsAManager": true,
        "IsActive": true,
        "SuperUserAccessLevel": 1,
        "FullName": "Sandip Vaidya"
      },
      "ColleagueSignOff": 1,
      "ManagerSignOff": 1,
      "Status": 1,
      "MeetingDate": "2017-01-10T13:53:00",
      "ColleagueSignedOffDate": "2017-01-10T13:55:10.483",
      "ManagerSignedOffDate": "2017-01-10T13:56:34.71",
      "SharingStatus": 1,
      "SharingDate": "2017-01-10T13:55:10.483",
      "FinancialYear": "2016-17"
    }
  ],
  "UpcomingMeetings": [],
  "PastMeetings": [],
  "LatestMeeting": null,
  "LastInCompleteMeeting": null,
  "LastMeeting": null,
  "MeetingsInLast12Months": 0
};